# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 222354660ee1d3aaaa739de85276f9a1595d8d9eef53327a8ff28bee053e53705923630439c65220633e8bc6bf7b904a6ec6bcd00cc2227c3e9be21e86f88696

test:
  secret_key_base: c64ef138195f3158037a7e93618406348809357d2982c9da811e155f8d40d6af679964ed0d207ee726eb3d0db18575c67aee2eb4b5ebfb8ea6f942536bd8961e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
